name = "GreedyAlign"
uuid = "e9a496d4-a0ac-4054-a7cc-e43b6064761e"
authors = ["Shane Kuei-Hsien Chu (skchu@wustl.edu)"]
version = "0.1.0"

[compat]
julia = "1.8.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
